{{- if .Values.pki.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ironroot.pkiSecretName" . }}
  labels:
    {{- include "ironroot.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-ca.crt: {{ .Values.pki.rootCa | quote }}
  ca-chain.crt: {{ .Values.pki.caChain | quote }}
  intermediate.crt: {{ .Values.pki.intermediateCert | quote }}
  intermediate.key: {{ .Values.pki.intermediateKey | quote }}
{{- end }}
{{- if and .Values.tls.enabled .Values.tls.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ironroot.tlsSecretName" . }}
  labels:
    {{- include "ironroot.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{ .Values.tls.cert | quote }}
  tls.key: {{ .Values.tls.key | quote }}
{{- end }}
