apiVersion: v1
kind: Service
metadata:
  name: {{ include "ironroot.fullname" . }}
  labels:
    {{- include "ironroot.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.config.telemetry.prometheus.enabled }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.config.telemetry.prometheus.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.config.telemetry.prometheus.path | quote }}
    prometheus.io/port: {{ .Values.service.port | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "ironroot.selectorLabels" . | nindent 4 }}
