package dev

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type DevInitOptions struct {
	Repo    string
	Output  string
	Force   bool
	DryRun  bool
	Verbose bool
	Stdout  io.Writer
	Stderr  io.Writer
}

type DevInitResult struct {
	BaseDir   string
	Workspace string
	Created   []string
	Existing  []string
	Written   []string
	Skipped   []string
}

func RunDevInit(ctx context.Context, opts DevInitOptions) error {
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}
	if opts.Stderr == nil {
		opts.Stderr = io.Discard
	}
	if strings.TrimSpace(opts.Output) == "" {
		opts.Output = ".localdev"
	}

	baseDir, err := resolveBaseDir(opts.Repo)
	if err != nil {
		return err
	}
	workspace := resolveWorkspace(baseDir, opts.Output)

	result := DevInitResult{BaseDir: baseDir, Workspace: workspace}
	if opts.DryRun {
		fmt.Fprintln(opts.Stdout, "DRY RUN: no files will be created or modified.")
	}

	dirs := []string{
		"config",
		"data",
		"pki",
		filepath.Join("pki", "root"),
		filepath.Join("pki", "intermediate"),
		"certs",
		"logs",
		"tmp",
	}
	for _, rel := range dirs {
		if err := ctx.Err(); err != nil {
			return err
		}
		path := filepath.Join(workspace, rel)
		created, err := ensureDir(path, opts.DryRun)
		if err != nil {
			return fmt.Errorf("failed to create local development directory %s: %w", path, err)
		}
		if created {
			result.Created = append(result.Created, path)
		} else {
			result.Existing = append(result.Existing, path)
		}
	}

	config := renderLocalConfig(workspace)
	if err := writeGeneratedFile(filepath.Join(workspace, "config", "config.yaml"), []byte(config), 0o644, opts.Force, opts.DryRun, &result); err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(workspace, ".gitignore"), []byte(localGitignore()), 0o644, opts.Force, opts.DryRun, &result); err != nil {
		return err
	}
	if err := writeGeneratedFile(filepath.Join(workspace, "README.txt"), []byte(localReadme()), 0o644, opts.Force, opts.DryRun, &result); err != nil {
		return err
	}

	printDevInitSummary(opts.Stdout, result, opts)
	return nil
}

func resolveBaseDir(repo string) (string, error) {
	if strings.TrimSpace(repo) != "" {
		abs, err := filepath.Abs(repo)
		if err != nil {
			return "", fmt.Errorf("failed to resolve --repo path: %w", err)
		}
		return abs, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("failed to read current directory: %w", err)
	}
	return wd, nil
}

func resolveWorkspace(repoRoot, output string) string {
	if filepath.IsAbs(output) {
		return filepath.Clean(output)
	}
	return filepath.Join(repoRoot, output)
}

func ensureDir(path string, dryRun bool) (bool, error) {
	info, err := os.Stat(path)
	if err == nil {
		if !info.IsDir() {
			return false, fmt.Errorf("path exists but is not a directory")
		}
		return false, nil
	}
	if !os.IsNotExist(err) {
		return false, err
	}
	if dryRun {
		return true, nil
	}
	if err := os.MkdirAll(path, 0o755); err != nil {
		return false, err
	}
	return true, nil
}

func writeGeneratedFile(path string, data []byte, perm os.FileMode, force, dryRun bool, result *DevInitResult) error {
	if exists(path) && !force {
		result.Skipped = append(result.Skipped, path)
		return nil
	}
	if dryRun {
		result.Written = append(result.Written, path)
		return nil
	}
	if err := os.WriteFile(path, data, perm); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	result.Written = append(result.Written, path)
	return nil
}

func renderLocalConfig(workspace string) string {
	config := embeddedLocalConfig
	replacements := map[string]string{
		"file:.localdev/data/ironroot.db":                  "file:" + filepath.ToSlash(filepath.Join(workspace, "data", "ironroot.db")),
		`".localdev/pki/root/root-ca.crt"`:                 quoteYAMLPath(filepath.Join(workspace, "pki", "root", "root-ca.crt")),
		`".localdev/pki/intermediate/ca-chain.crt"`:        quoteYAMLPath(filepath.Join(workspace, "pki", "intermediate", "ca-chain.crt")),
		`".localdev/pki/intermediate/intermediate-ca.crt"`: quoteYAMLPath(filepath.Join(workspace, "pki", "intermediate", "intermediate-ca.crt")),
		`".localdev/pki/intermediate/intermediate-ca.key"`: quoteYAMLPath(filepath.Join(workspace, "pki", "intermediate", "intermediate-ca.key")),
	}
	for old, newValue := range replacements {
		config = strings.ReplaceAll(config, old, newValue)
	}
	return config
}

func quoteYAMLPath(path string) string {
	return `"` + strings.ReplaceAll(filepath.ToSlash(path), `"`, `\"`) + `"`
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func localGitignore() string {
	return "*\n!.gitignore\n!README.txt\n"
}

func localReadme() string {
	return strings.Join([]string{
		"IronRoot local development workspace",
		"",
		"Generated by: ironroot-dev dev-init",
		"",
		"Directories:",
		"- config/       generated local config with absolute PKI and SQLite paths",
		"- data/         SQLite database",
		"- pki/root/     local Root CA material created by ironroot-admin",
		"- pki/intermediate/ local Intermediate CA material created by ironroot-admin",
		"- certs/        requested certificates; DNS-specific directories are created later",
		"- logs/         optional local logs",
		"- tmp/          temporary local development files",
		"",
		"This directory is ignored by Git. Do not commit generated keys, certs, tokens, or databases.",
		"",
	}, "\n")
}

func printDevInitSummary(w io.Writer, result DevInitResult, opts DevInitOptions) {
	fmt.Fprintln(w, "IronRoot local development workspace initialized.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "Base directory:\n%s\n\n", result.BaseDir)
	fmt.Fprintf(w, "Workspace:\n%s\n\n", result.Workspace)
	if len(result.Created) > 0 {
		label := "Created:"
		if opts.DryRun {
			label = "Would create:"
		}
		fmt.Fprintln(w, label)
		for _, path := range result.Created {
			fmt.Fprintf(w, "- %s\n", path)
		}
		fmt.Fprintln(w)
	}
	if len(result.Written) > 0 {
		label := "Written:"
		if opts.DryRun {
			label = "Would write:"
		}
		fmt.Fprintln(w, label)
		for _, path := range result.Written {
			fmt.Fprintf(w, "- %s\n", path)
		}
		fmt.Fprintln(w)
	}
	if opts.Verbose && len(result.Existing) > 0 {
		fmt.Fprintln(w, "Already exists:")
		for _, path := range result.Existing {
			fmt.Fprintf(w, "- %s\n", path)
		}
		fmt.Fprintln(w)
	}
	if len(result.Skipped) > 0 {
		fmt.Fprintln(w, "Skipped existing files:")
		for _, path := range result.Skipped {
			fmt.Fprintf(w, "- %s\n", path)
		}
		fmt.Fprintln(w, "Use --force to regenerate these files.")
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "Next steps:")
	fmt.Fprintln(w, "1. Generate a local Root CA")
	fmt.Fprintln(w, "2. Generate a local Intermediate CA")
	fmt.Fprintln(w, "3. Start ironroot-server")
	fmt.Fprintln(w, "4. Run local tests")
}

const embeddedLocalConfig = `server:
  address: "localhost:8443"
  tls:
    cert_file: ""
    key_file: ""
database:
  driver: sqlite
  dsn: "file:.localdev/data/ironroot.db?_foreign_keys=on"
pki:
  root_file: ".localdev/pki/root/root-ca.crt"
  chain_file: ".localdev/pki/intermediate/ca-chain.crt"
  intermediate_cert_file: ".localdev/pki/intermediate/intermediate-ca.crt"
  intermediate_key_file: ".localdev/pki/intermediate/intermediate-ca.key"
  intermediate_key_pass: "ironroot-local-intermediate"
  default_lifetime: 2160h
  renew_before: 720h
telemetry:
  enabled: false
  service_name: ironroot-local
  deployment_environment: local
  prometheus:
    enabled: true
    path: /metrics
log:
  level: info
`
