apiVersion: v1
kind: Secret
metadata:
  name: ironroot-ca
  labels:
    app.kubernetes.io/name: ironroot
    app.kubernetes.io/component: pki-server
type: Opaque
stringData:
  root-ca.crt: ""
  ca-chain.crt: ""
  intermediate.crt: ""
  intermediate.key: ""

